### ISSUE TITLE
'_blind_trust' is not defined: Error on execution

### ISSUE THREAD

**Issue by geoffwhittington** [jdewinne/xlr-sdelements-plugin#2]
I hit an error running the plugin v2.0.0 with XL Release Version 8.0.0. All required fields are filled; including global configuration.

```
Script failed. Exception during execution:
NameError: global name '_blind_trust' is not defined in <script> at line number 17
```

**Comment by jdewinne** [comment]
Thanks. Could you try [v2.0.1](https://github.com/xebialabs-community/xlr-sdelements-plugin/releases/tag/v2.0.1) on the xebialabs-community organization?

**Comment by geoffwhittington** [comment]
That addressed the issue, thanks!
